import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 지식 베이스 사이드바.
 *
 * autogenerated 방식이라, docs/ 아래에 폴더(주제)나 .md 파일을 추가하면
 * 사이드바에 자동으로 나타난다. 순서/카테고리 이름은 각 폴더의
 * _category_.json 으로 제어한다. 손으로 이 파일을 고칠 필요가 거의 없다.
 */
const sidebars: SidebarsConfig = {
  knowledgeSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
